### ISSUE TITLE
Multiply-authored topics list authors separately

### ISSUE THREAD

**Issue by alesage** [brianray/Chipy#10]
When topics are co-authored by two or more presenters, we're presently using their joint name to represent authorship, e.g. "William Scullin and James P. Snyder"; instead, list the authors separately as "William Scullin" and "James P. Snyder" so that their individual contributions will be respected.  In particular, in the admin, a listing of the meetings of either should turn up multiply-presented topics as well as singly-presented topics.

**Comment by brianray** [comment]
Nice. Agreed the current implementation only supports one. You (who
ever implements) will want to create a migration script an put the
authors where we listed two in separate entries. Test when running
against a current data set.

**Comment by paaschpa** [comment]
- put a many to many on Topic 
- added a sql migration file
