### ISSUE TITLE
Embed better maps

### ISSUE THREAD

**Issue by alesage** [brianray/Chipy#2]
Per Brian Ray's recommendation, embed better maps for the various ChiPy locations.

**Comment by aphor** [comment]
I vote AJAX, search as you type, and Google Maps API embedding.

**Comment by aphor** [comment]
git://github.com/aphor/Chipy.git
Switched to Google Maps API v3 for the map rendering. I didn't do anything with the location search/geocoding which is ostensibly coming from Yahoo APIs still, and IMHO still sucks. The good news is that they seem to be playing nice with each other.

Allen, if you would, please take a look at my fork's changes and merge them into the master repo? Feel free to make whatever changes. I was having trouble with Xcode auto indent, so there may be some style issues.
