### ISSUE TITLE
discuss restful interface design

### ISSUE THREAD

**Issue by codersquid** [brianray/Chipy#21]
I'd like to discuss this so that we end up with a sane and clean  interface for some of the features being proposed in the issues here. Here are some thoughts I'll toss out to begin.

GETs: I'd like to be able to get a resource to meetings, speakers, packages, venues, sponsors, &tc. I'd like to be able to get the resources in various forms, e.g. text friendly for printing or a mobile view, programmatically friendly for use with scripts &tc.

POSTs: I'd like to be able to submit metadata to some of the above.  We would want auth scheme for some of this or I suppose we could alternatively have a moderating queue. One thing that would be kick-ass would be an ability to send chipy posts from the mailing list when we discuss meetings and have them scraped for metadata.

**Comment by alesage** [comment]
We could use something like [django-piston](http://www.mefeedia.com/watch/28374198) for this?

**Comment by paaschpa** [comment]
- need django-piston
- still kind of a work-in-progress
- added route to /api/meetings/?format={json/xml} & /api/meetings/{id}/?format={json/xml}
- added route to /api/presentors/?format={json/xml} & /api/presentor/{id}/?format={json/xml}
