### ISSUE TITLE
Can not add new meetings

### ISSUE THREAD

**Issue by brianray** [brianray/Chipy#28]
NameError at /admin/meetings/meeting/add/
global name 'Subject' is not defined /app/chipy_org/apps/meetings/models.py in save, line 86

Complete traceback is attached.

**Comment by brianray** [comment]
Could not attach file in github so cut and pasting :

NameError at /admin/meetings/meeting/add/
global name 'Subject' is not defined
Request Method: POST
Request URL:    http://www.chipy.org/admin/meetings/meeting/add/
Django Version: 1.4.3
Exception Type: NameError
Exception Value:  
global name 'Subject' is not defined
Exception Location: /app/chipy_org/apps/meetings/models.py in save, line 86
Python Executable:  /app/.heroku/python/bin/python
Python Version: 2.7.3
Python Path:  
['/app/chipy_org',
 '/app/.heroku/python/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg',
 '/app/.heroku/python/lib/python2.7/site-packages/pip-1.1-py2.7.egg',
 '/app',
 '/app/.heroku/python/lib/python27.zip',
 '/app/.heroku/python/lib/python2.7',
 '/app/.heroku/python/lib/python2.7/plat-linux2',
 '/app/.heroku/python/lib/python2.7/lib-tk',
 '/app/.heroku/python/lib/python2.7/lib-old',
 '/app/.heroku/python/lib/python2.7/lib-dynload',
 '/app/.heroku/python/lib/python2.7/site-packages',
 '/app/.heroku/python/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg-info',
 '/app/chipy_org/apps',
 '/app/chipy_org/apps',
 '/app/chipy_org/apps']
Server time:    Mon, 18 Mar 2013 11:57:02 -0500
Traceback Switch to copy-and-paste view

/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py in get_response
                        response = callback(request, _callback_args, *_callback_kwargs) ...
▶ Local vars
/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py in wrapper
                return self.admin_site.admin_view(view)(_args, *_kwargs) ...
▶ Local vars
/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, _args, *_kwargs) ...
▶ Local vars
/app/.heroku/python/lib/python2.7/site-packages/django/views/decorators/cache.py in _wrapped_view_func
        response = view_func(request, _args, *_kwargs) ...
▶ Local vars
/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/sites.py in inner
            return view(request, _args, *_kwargs) ...
▶ Local vars
/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py in _wrapper
            return bound_func(_args, *_kwargs) ...
▶ Local vars
/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py in _wrapped_view
                    response = view_func(request, _args, *_kwargs) ...
▶ Local vars
/app/.heroku/python/lib/python2.7/site-packages/django/utils/decorators.py in bound_func
                return func(self, _args2, *_kwargs2) ...
▶ Local vars
/app/.heroku/python/lib/python2.7/site-packages/django/db/transaction.py in inner
                return func(_args, *_kwargs) ...
▶ Local vars
/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py in add_view
                self.save_model(request, new_object, form, False) ...
▶ Local vars
/app/.heroku/python/lib/python2.7/site-packages/django/contrib/admin/options.py in save_model
        obj.save() ...
▶ Local vars
/app/chipy_org/apps/meetings/models.py in save
        return super(Subject, self).save(_args, *_kwargs) ...
▶ Local vars
Request information

GET
No GET data
POST
Variable    Value
where  
u'3'
key 
u'threadlessmakesniceshirtsyo'
csrfmiddlewaretoken 
u'VzMb6sanCW6GWceMtOnHqumDXbojRtNI'
_continue  
u'Save and continue editing'
when_1  
u'19:00:00'
when_0  
u'2013-04-11'
FILES
No FILES data
COOKIES
Variable    Value
csrftoken  
'VzMb6sanCW6GWceMtOnHqumDXbojRtNI'
__utma  
'214944197.752849013.1334061271.1361143347.1361147251.390'
__utmz  
'214944197.1359073829.360.14.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)'
sessionid  
'1401715cc11cdaacd60ae8d26da17bc7'
META
Variable    Value
HTTP_X_FORWARDED_FOR  
'209.249.208.50'
HTTP_CACHE_CONTROL  
'max-age=0'
HTTP_ACCEPT_LANGUAGE  
'en-US,en;q=0.8'
HTTP_X_HEROKU_DYNOS_IN_USE  
'1'
HTTP_ACCEPT 
'text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8'
gunicorn.socket 
<socket._socketobject object at 0x16f9130>
wsgi.input  
<gunicorn.http.body.Body object at 0x16e7c50>
HTTP_USER_AGENT 
'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_8) AppleWebKit/537.22 (KHTML, like Gecko) Chrome/25.0.1364.172 Safari/537.22'
wsgi.version  
(1, 0)
CONTENT_TYPE  
'multipart/form-data; boundary=----WebKitFormBoundaryAdZQpbsnikbDR43B'
SERVER_PROTOCOL 
'HTTP/1.1'
wsgi.run_once  
False
wsgi.file_wrapper  
''
SERVER_SOFTWARE 
'gunicorn/0.17.2'
HTTP_ACCEPT_ENCODING  
'gzip,deflate,sdch'
SCRIPT_NAME 
u''
SERVER_NAME 
'www.chipy.org'
wsgi.url_scheme 
'http'
HTTP_ACCEPT_CHARSET 
'ISO-8859-1,utf-8;q=0.7,_;q=0.3'
REMOTE_PORT 
'54677'
REMOTE_ADDR 
'10.227.18.70'
wsgi.errors 
<open file '<stderr>', mode 'w' at 0x7f0de07cb270>
wsgi.multiprocess  
True
HTTP_CONNECTION 
'close'
CONTENT_LENGTH  
'717'
HTTP_ORIGIN 
'http://www.chipy.org'
HTTP_X_REQUEST_START  
'1363625822264'
REQUEST_METHOD  
'POST'
HTTP_REFERER  
'http://www.chipy.org/admin/meetings/meeting/add/'
HTTP_COOKIE 
'__utma=214944197.752849013.1334061271.1361143347.1361147251.390; __utmz=214944197.1359073829.360.14.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided); sessionid=1401715cc11cdaacd60ae8d26da17bc7; csrftoken=VzMb6sanCW6GWceMtOnHqumDXbojRtNI'
QUERY_STRING  
''
HTTP_X_FORWARDED_PROTO  
'http'
HTTP_X_HEROKU_QUEUE_DEPTH  
'0'
HTTP_X_HEROKU_QUEUE_WAIT_TIME  
'0'
PATH_INFO  
u'/admin/meetings/meeting/add/'
CSRF_COOKIE 
'VzMb6sanCW6GWceMtOnHqumDXbojRtNI'
SERVER_PORT 
'80'
HTTP_X_FORWARDED_PORT  
'80'
HTTP_HOST  
'www.chipy.org'
RAW_URI 
'/admin/meetings/meeting/add/'
wsgi.multithread  
False
Settings
Using settings module chipy_org.settings
Setting Value
USE_ETAGS  
False
APPEND_SLASH  
True
SESSION_EXPIRE_AT_BROWSER_CLOSE 
False
SITE_ID 
1
HONEYPOT_FIELD_NAME 
'email2'
ALLOWED_INCLUDE_ROOTS  
()
SOCIAL_AUTH_PIPELINE  
('social_auth.backends.pipeline.social.social_auth_user',
 'social_auth.backends.pipeline.user.get_username',
 'libs.social_auth_pipelines.create_user',
 'social_auth.backends.pipeline.social.associate_user',
 'social_auth.backends.pipeline.social.load_extra_data',
 'social_auth.backends.pipeline.user.update_user_details')
TIME_FORMAT 
'P'
DEFAULT_INDEX_TABLESPACE  
''
LANGUAGES  
(('ar', 'Arabic'),
 ('az', 'Azerbaijani'),
 ('bg', 'Bulgarian'),
 ('bn', 'Bengali'),
 ('bs', 'Bosnian'),
 ('ca', 'Catalan'),
 ('cs', 'Czech'),
 ('cy', 'Welsh'),
 ('da', 'Danish'),
 ('de', 'German'),
 ('el', 'Greek'),
 ('en', 'English'),
 ('en-gb', 'British English'),
 ('eo', 'Esperanto'),
 ('es', 'Spanish'),
 ('es-ar', 'Argentinian Spanish'),
 ('es-mx', 'Mexican Spanish'),
 ('es-ni', 'Nicaraguan Spanish'),
 ('et', 'Estonian'),
 ('eu', 'Basque'),
 ('fa', 'Persian'),
 ('fi', 'Finnish'),
 ('fr', 'French'),
 ('fy-nl', 'Frisian'),
 ('ga', 'Irish'),
 ('gl', 'Galician'),
 ('he', 'Hebrew'),
 ('hi', 'Hindi'),
 ('hr', 'Croatian'),
 ('hu', 'Hungarian'),
 ('id', 'Indonesian'),
 ('is', 'Icelandic'),
 ('it', 'Italian'),
 ('ja', 'Japanese'),
 ('ka', 'Georgian'),
 ('kk', 'Kazakh'),
 ('km', 'Khmer'),
 ('kn', 'Kannada'),
 ('ko', 'Korean'),
 ('lt', 'Lithuanian'),
 ('lv', 'Latvian'),
 ('mk', 'Macedonian'),
 ('ml', 'Malayalam'),
 ('mn', 'Mongolian'),
 ('nb', 'Norwegian Bokmal'),
 ('ne', 'Nepali'),
 ('nl', 'Dutch'),
 ('nn', 'Norwegian Nynorsk'),
 ('pa', 'Punjabi'),
 ('pl', 'Polish'),
 ('pt', 'Portuguese'),
 ('pt-br', 'Brazilian Portuguese'),
 ('ro', 'Romanian'),
 ('ru', 'Russian'),
 ('sk', 'Slovak'),
 ('sl', 'Slovenian'),
 ('sq', 'Albanian'),
 ('sr', 'Serbian'),
 ('sr-latn', 'Serbian Latin'),
 ('sv', 'Swedish'),
 ('sw', 'Swahili'),
 ('ta', 'Tamil'),
 ('te', 'Telugu'),
 ('th', 'Thai'),
 ('tr', 'Turkish'),
 ('tt', 'Tatar'),
 ('uk', 'Ukrainian'),
 ('ur', 'Urdu'),
 ('vi', 'Vietnamese'),
 ('zh-cn', 'Simplified Chinese'),
 ('zh-tw', 'Traditional Chinese'))
MONTH_DAY_FORMAT  
'F j'
FIRST_DAY_OF_WEEK  
0
TEMPLATE_STRING_IF_INVALID  
''
FILE_UPLOAD_PERMISSIONS 
None
DEBUG  
True
DEFAULT_EXCEPTION_REPORTER_FILTER  
'django.views.debug.SafeExceptionReporterFilter'
LANGUAGES_BIDI  
('he', 'ar', 'fa')
USE_X_FORWARDED_HOST  
False
CSRF_COOKIE_DOMAIN  
None
SECRET_KEY  
u'_******************_'
USE_TZ  
False
EMAIL_HOST  
'smtp.sendgrid.net'
SIGNING_BACKEND 
'django.core.signing.TimestampSigner'
DEFAULT_CONTENT_TYPE  
'text/html'
CSRF_FAILURE_VIEW  
'django.views.csrf.csrf_failure'
DEBUG_PROPAGATE_EXCEPTIONS  
False
SESSION_COOKIE_NAME 
'sessionid'
STATICFILES_STORAGE 
'django.contrib.staticfiles.storage.StaticFilesStorage'
ADMINS  
[('emperorcezar', 'emperorcezar@gmail.com')]
PREPEND_WWW 
True
STATIC_ROOT 
'/app/chipy_org/site_media/static'
PASSWORD_RESET_TIMEOUT_DAYS 
u'**_****************_'
MEDIA_ROOT  
'/app/chipy_org/site_media/media'
NUMBER_GROUPING 
0
DATE_FORMAT 
'N j, Y'
DATABASE_ROUTERS  
[]
SESSION_COOKIE_PATH 
'/'
GITHUB_APP_ID  
'eeb6457e4d9756b79375'
SOCIAL_AUTH_ENABLED_BACKENDS  
('google', 'github')
TIME_ZONE  
'US/Central'
DATETIME_FORMAT 
'N j, Y, P'
DEFAULT_CHARSET 
'utf-8'
SESSION_COOKIE_AGE  
1209600
TEST_RUNNER 
'django.test.simple.DjangoTestSuiteRunner'
CACHE_MIDDLEWARE_KEY_PREFIX 
u'**_****************_'
TRANSACTIONS_MANAGED  
False
ADMIN_FOR  
()
DECIMAL_SEPARATOR  
'.'
FILE_CHARSET  
'utf-8'
USE_I18N  
False
SESSION_COOKIE_SECURE  
False
MESSAGE_STORAGE 
'django.contrib.messages.storage.session.SessionStorage'
SERVER_EMAIL  
'root@localhost'
LOGGING_CONFIG  
'django.utils.log.dictConfig'
CACHE_MIDDLEWARE_SECONDS  
600
SECURE_PROXY_SSL_HEADER 
None
URL_VALIDATOR_USER_AGENT  
'Django/1.4.3 (https://www.djangoproject.com)'
TEMPLATE_LOADERS  
['django.template.loaders.filesystem.Loader',
 'django.template.loaders.app_directories.Loader']
SHORT_DATE_FORMAT  
'm/d/Y'
DEFAULT_TABLESPACE  
''
FORCE_SCRIPT_NAME  
None
FILE_UPLOAD_HANDLERS  
('django.core.files.uploadhandler.MemoryFileUploadHandler',
 'django.core.files.uploadhandler.TemporaryFileUploadHandler')
ABSOLUTE_URL_OVERRIDES  
{}
LANGUAGE_CODE  
'en-us'
ADMIN_MEDIA_PREFIX  
'/site_media/static/admin/'
IGNORABLE_404_URLS  
()
WSGI_APPLICATION  
None
ROOT_URLCONF  
'chipy_org.urls'
ENVELOPE_EMAIL_RECIPIENTS  
['emperorcezar@gmail.com', 'brianhray@gmail.com']
USE_L10N  
False
LOGOUT_URL  
'/accounts/logout/'
PROFANITIES_LIST  
u'**_****************_'
SESSION_ENGINE  
'django.contrib.sessions.backends.db'
TIME_INPUT_FORMATS  
('%H:%M:%S', '%H:%M')
DATABASES  
{'default': {'ENGINE': 'django.db.backends.postgresql_psycopg2',
             'HOST': 'ec2-23-21-209-165.compute-1.amazonaws.com',
             'NAME': 'db298nask7l6pu',
             'PASSWORD': u'**_****************_',
             'PORT': 5432,
             'USER': 'zfecdywcwtcdfa'}}
LANGUAGE_COOKIE_NAME  
'django_language'
CSRF_COOKIE_NAME  
'csrftoken'
TINYMCE_DEFAULT_CONFIG  
{'content_css': '/site_media/media/css/custom_tinymce.css',
 'height': '500',
 'plugins': 'table,spellchecker,paste,searchreplace',
 'relative_urls': False,
 'theme': 'advanced'}
MIDDLEWARE_CLASSES  
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'libs.middleware.ChipySocialAuthExceptionMiddleware')
FILE_UPLOAD_TEMP_DIR  
None
PROJECT_ROOT  
'/app/chipy_org'
SERVE_MEDIA 
True
DEFAULT_FILE_STORAGE  
'django.core.files.storage.FileSystemStorage'
TEMPLATE_DIRS  
['/app/chipy_org/templates']
STATICFILES_DIRS  
['/app/chipy_org/static']
SESSION_COOKIE_DOMAIN  
None
STATIC_URL  
'/site_media/static/'
FORMAT_MODULE_PATH  
None
X_FRAME_OPTIONS 
'SAMEORIGIN'
PASSWORD_HASHERS  
u'**_****************_'
SETTINGS_MODULE 
'chipy_org.settings'
CACHES  
{'default': {'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
             'LOCATION': ''}}
SEND_BROKEN_LINK_EMAILS 
False
LOGGING 
{'disable_existing_loggers': False,
 'filters': {'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'}},
 'handlers': {'mail_admins': {'class': 'django.utils.log.AdminEmailHandler',
                              'filters': ['require_debug_false'],
                              'level': 'ERROR'}},
 'loggers': {'django.request': {'handlers': ['mail_admins'],
                                'level': 'ERROR',
                                'propagate': True}},
 'version': 1}
LOGIN_REDIRECT_URL  
'/'
LOGIN_ERROR_URL 
'/'
AUTHENTICATION_BACKENDS 
('social_auth.backends.twitter.TwitterBackend',
 'social_auth.backends.facebook.FacebookBackend',
 'social_auth.backends.google.GoogleBackend',
 'social_auth.backends.browserid.BrowserIDBackend',
 'social_auth.backends.contrib.linkedin.LinkedinBackend',
 'social_auth.backends.contrib.github.GithubBackend',
 'social_auth.backends.OpenIDBackend',
 'django.contrib.auth.backends.ModelBackend')
GITHUB_API_SECRET  
u'**_****************_'
CSRF_COOKIE_PATH  
'/'
CACHE_MIDDLEWARE_ALIAS  
'default'
FILE_UPLOAD_MAX_MEMORY_SIZE 
2621440
DATETIME_INPUT_FORMATS  
('%Y-%m-%d %H:%M:%S',
 '%Y-%m-%d %H:%M:%S.%f',
 '%Y-%m-%d %H:%M',
 '%Y-%m-%d',
 '%m/%d/%Y %H:%M:%S',
 '%m/%d/%Y %H:%M:%S.%f',
 '%m/%d/%Y %H:%M',
 '%m/%d/%Y',
 '%m/%d/%y %H:%M:%S',
 '%m/%d/%y %H:%M:%S.%f',
 '%m/%d/%y %H:%M',
 '%m/%d/%y')
EMAIL_BACKEND  
'django.core.mail.backends.smtp.EmailBackend'
USE_THOUSAND_SEPARATOR  
False
TEMPLATE_DEBUG  
True
COMMENTS_ALLOW_PROFANITIES  
False
INTERNAL_IPS  
['127.0.0.1']
SESSION_COOKIE_HTTPONLY 
True
EMAIL_HOST_USER 
'app6296422@heroku.com'
SESSION_SAVE_EVERY_REQUEST  
False
MANAGERS  
[('emperorcezar', 'emperorcezar@gmail.com')]
EMAIL_USE_TLS  
True
EMAIL_PORT  
587
DATE_INPUT_FORMATS  
('%Y-%m-%d',
 '%m/%d/%Y',
 '%m/%d/%y',
 '%b %d %Y',
 '%b %d, %Y',
 '%d %b %Y',
 '%d %b, %Y',
 '%B %d %Y',
 '%B %d, %Y',
 '%d %B %Y',
 '%d %B, %Y')
INSTALLED_APPS  
['grappelli',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.humanize',
 'django.contrib.staticfiles',
 'django.contrib.flatpages',
 'social_auth',
 'gunicorn',
 'interval',
 'gravatar',
 'flatblocks',
 'tinymce',
 'flatpages_tinymce',
 'honeypot',
 'south',
 'envelope',
 'django_forms_bootstrap',
 'about',
 'meetings',
 'profiles',
 'contact',
 'django_extensions']
CACHE_BACKEND  
'locmem://'
TEMPLATE_CONTEXT_PROCESSORS 
['django.contrib.auth.context_processors.auth',
 'django.core.context_processors.debug',
 'django.core.context_processors.i18n',
 'django.core.context_processors.media',
 'django.core.context_processors.request',
 'django.core.context_processors.static',
 'django.contrib.messages.context_processors.messages',
 'social_auth.context_processors.social_auth_login_redirect']
THOUSAND_SEPARATOR  
','
FIXTURE_DIRS  
['/app/chipy_org/fixtures']
STATICFILES_FINDERS 
['django.contrib.staticfiles.finders.FileSystemFinder',
 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
LOCALE_PATHS  
()
YEAR_MONTH_FORMAT  
'F Y'
DISALLOWED_USER_AGENTS  
()
MEDIA_URL  
'/site_media/media/'
EMAIL_SUBJECT_PREFIX  
'[Django] '
LOGIN_URL  
'/login/'
SESSION_FILE_PATH  
None
EMAIL_HOST_PASSWORD 
u'**_*****************'
SOCIAL_AUTH_PROTECTED_USER_FIELDS  
['email', 'first_name', 'last_name']
CSRF_COOKIE_SECURE  
False
DEFAULT_FROM_EMAIL  
'DoNotReply@chipy.org'
SHORT_DATETIME_FORMAT  
'm/d/Y P'
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 500 page.

**Comment by emperorcezar** [comment]
Ha, that very strange how that got there. Pushing an update now. Check it if you could?

**Comment by brianray** [comment]
Looks good
