### ISSUE TITLE
RSVP/Maybe Buttons Meeting Widget

### ISSUE THREAD

**Issue by alesage** [brianray/Chipy#3]
A button via which a user can signal his/her intention to attend a meeting.  Per an initial Brian Ray communique:

> This widget should keep a table entry (add a model) for RSVP that
> relates to a User and Meeting.  Always show the button if the meeting
> is in the future.  If they are not logged in and they click, redirect
> them to create a login first.

**Comment by alesage** [comment]
Further notes from a conversation with Brian:
- The user should not be asked to login unless they have already hit
  the RSVP or Maybe button.
- The behavior-pattern may be similar to the Facebook "events" button:
  e.g. the "attending?", "followed by", or "yes" button, with the
  proviso that these opt-ins must be linked to an existing account--if
  the user has no account, then he/she must make one.
- NOTE that this task does not include showing a list of RSVPs for a
  given meeting, however the creation of the model mentioned above should facilitate such.
- Streamline user-interaction (in the existing-account case) to a maximum of two
  clicks by the user.

**Comment by DanAdamSchmidt** [comment]
Hey Allan, this is my(Dan Schmidt's) account on GitHub. Saw ya mention that I needed to be assigned to this task so I thought you might need to know my account name.

**Comment by alesage** [comment]
Super, I believe that only Brian has teh perms at the moment, you might want
to send him a similar message?

Allan
