### ISSUE TITLE
Multiple topics do not sort by start time on main page

### ISSUE THREAD

**Issue by brianray** [brianray/Chipy#30]
(Matt's starts later so the other should be on the top)

This Month's Topics

Using PyJnius to talk to Android devices
(30 Minutes)
By: Matt Dorn
Overview of a library that facilitates communication with Android devices via Python -- depending on interest, could include an overview of other Python/Java libraries and/or other ways to use Python with Android.
Python Deployments at The Onion (and elsewhere)
(30 Minutes)

By: Chris Sinchok
Chris will cover various Python deployment strategies and technologies, ranging from the naïve (git pull) to the more robust (fabric, capistrano) to the "Enterprise" (Python native package deployments, etc). In order to illustrate these different strategies and technologies, he will take examples from my past projects, and the constantly-evolving Onion deploy process.

**Comment by emperorcezar** [comment]
This should be fixed now.
