### ISSUE TITLE
Swaps tab gives 500 error

### ISSUE THREAD

**Issue by saschwarz** [brianray/Chipy#7]
1. Login
2. click on Swaps tab: http://chipy.org/swaps/
3. Server error is reported.

**Comment by alesage** [comment]
I'm not able to reproduce this locally, but I can confirm that it happens in production.

I dug around on production logs and found `[error] [client 208.54.94.55] File does not exist: /home/chipy/wwwchipy/media/uni_form, referer: http://www.chipy.org/swaps/` --I wonder if this explains?  No such error occurs on local.  Can dig further but need some infos from Brian re: the server environment.

**Comment by brianray** [comment]
I think originally I thought it would be a good role for someone who wants to get a some server production type experience to be on the team. (other than me, hehe)  However, I think everyone currently on the team wants to do regular development, correct?  Regardless, for this particular issue I will take a look once I get a chance.

**Comment by bhaugen** [comment]
I made Swaps.  Nobody has used it much, it's just been hanging out there and may be out of date.  If chipy wants to use it, and you can use some help from me, let me know.  Unfortunately, I am not a production server jock, so I might not be useful in this particular situation.
